version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "9001:80"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
        - REDIS_PASSWORD=sunrint7194!